config/routes.rb
PhotogurRetry::Application.routes.draw do

  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController


    def index

        @pictures = Picture.all        

    end 


    def show

        @picture = Picture.find(params[:id])

    end 

    def new

        @picture = Picture.new

    end

    def create

        puts params.inspect
        @new_picture=Picture.new(picture_params)

        if @new_picture.save
            redirect_to pictures_url
        else
          render :new
        end 

    end 

    def edit

        @picture = Picture.find(params[:id])

    end 

    def update

        @picture = Picture.find(params[:id])

        if @picture.update_attributes(picture_params)

            redirect_to picture_url(params[:id])
        else 

            render :edit
        end

    end 

    def destroy

        Picture.find(params[:id]).destroy
        redirect_to pictures_url

    end 


    private

    def picture_params

        params.require(:picture).permit(:title,:year,:artist,:url)

    end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotogurRetry</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Update image information below:</h1>


<%= form_for @picture do |f| %>

    <p><%= f.label "title" %>
    <%= f.text_field "title" %></p>

    <p><%= f.label "artist" %>
    <%= f.text_field "artist" %></p>

    <p><%= f.label "year" %>
    <%= f.text_field "year" %></p>

    <p><%= f.label "url" %>
    <%= f.text_field "url" %></p>

    <p><%= f.submit "Update" %></p>

<% end %>

app/views/pictures/index.html.erb
<h1>Here are all the pictures</h1>

<%= link_to "Add a picture", new_picture_url %>

<% @pictures.each do |picture| %>

    <p><%= picture.title %> by <%= picture.artist %></p>
    <p><%= picture.year %></p>
    <%= link_to image_tag(picture.url), picture_url(picture.id) %>

<% end %>

app/views/pictures/new.html.erb
<h1>Enter image information below:</h1>


<%= form_for @picture do |f| %>

    <p><%= f.label "title" %>
    <%= f.text_field "title" %></p>

    <p><%= f.label "artist" %>
    <%= f.text_field "artist" %></p>

    <p><%= f.label "year" %>
    <%= f.text_field "year" %></p>

    <p><%= f.label "url" %>
    <%= f.text_field "url" %></p>

    <p><%= f.submit "Add" %></p>

<% end %>

app/views/pictures/show.html.erb
<h1>Here is the picture</h1>

    <p><%= link_to "Edit", edit_picture_url(@picture) %></p>
    <p><%= link_to "Delete", @picture, :method => "delete" %></p>
    <p><%= @picture.title %> by <%= @picture.artist %></p>
    <p><%= @picture.year %></p>
    <img src="<%= @picture.url %>" />